apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: busybox
    command: ['sh', '-c', 'env && sleep 3600']
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: db.user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: db.password
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "256Mi"


