apiVersion: v1
kind: Pod
metadata:
  name: pod-small-readwrite
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo "Hello from Kubernetes" > /usr/share/busybox/testfile && sleep 3600']
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
    volumeMounts:
    - mountPath: /usr/share/busybox
      name: small-readwrite-storage
  volumes:
  - name: small-readwrite-storage
    persistentVolumeClaim:
      claimName: pvc-small-readwrite

