apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-small-readwrite
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data-small"
